name: 'Dogu Slack'
description: 'Dogu Slack Template'
inputs:
  template:
    required: true
    description: 'Template name'
  slack-channel-id:
    required: true
    description: 'Slack channel id'
  is-fail:
    required: true
    description: 'Job fail'
runs:
  using: 'node16'
  main: 'dist/index.js'
