name: 'Dogu Slack'
description: 'Dogu Slack Template'
inputs:
  template:
    required: true
    description: 'Template name'
  slack-channel-id:
    required: true
    description: 'Slack channel id'
  is-succeed:
    required: true
    description: 'Job is succeed'
  ignore-notify:
    require: false
    description: 'Ignore Notify'

runs:
  using: 'node16'
  main: 'dist/index.js'
